import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from peft import PeftModel
from transformers import AutoTokenizer, AutoModelForMaskedLM
from sklearn.metrics import f1_score, classification_report
tokenizer = AutoTokenizer.from_pretrained("FacebookAI/xlm-roberta-base")
repo_name = "MarkProMaster229/experimental_models"
lora = "ForRoberta_models/loraForROBERTA_epoch4"

base_model = AutoModelForSequenceClassification.from_pretrained(
    "FacebookAI/xlm-roberta-base",
    num_labels=3,
    torch_dtype=torch.float32,
    device_map="cpu"
)

model = PeftModel.from_pretrained(base_model, repo_name, subfolder=lora)

def predict(text, model, tokenizer):
    model.eval()

    inputs = tokenizer(
        text,
        truncation=True,
        padding="max_length",
        max_length=128,
        return_tensors="pt"
    )

    with torch.no_grad():
        outputs = model(
            input_ids=inputs["input_ids"],
            attention_mask=inputs["attention_mask"]
        )

    logits = outputs.logits
    predicted_class = torch.argmax(logits, dim=-1).item()

    id2label = {0: "negative", 1: "neutral", 2: "positive"}
    confidence = torch.softmax(logits, dim=-1).max().item()

    return id2label[predicted_class], confidence


"""
ОСТОРОЖНО: АГРЕССИВНЫЙ КОНТЕНТ

Комментарии взяты из открытых источников, разметка выполнена LLM.
Содержимое комментариев - личные мнения тех людей, что их оставили.
Проект создан в исследовательских целях.
Разработчик не несёт ответственности за любые прямые или косвенные
последствия использования данных


WARNING: EXPLICIT/AGGRESSIVE CONTENT

Comments were collected from publicly available sources, with labels generated by an LLM.
The content of the comments reflects the personal opinions of their respective authors.
This project is intended for research purposes only.
All responsibility for the use of this data lies with the user.
The developer assumes no liability for any direct or indirect consequences arising from the use of this data.
"""

import json
import os

script_dir = os.path.dirname(os.path.abspath(__file__))
encoder_dir = os.path.dirname(script_dir)
ml_lab_dir = os.path.dirname(encoder_dir)
json_path = os.path.join(ml_lab_dir, "TestMyWork", "ThisToxicClassificationiMsoSorry.json")

with open(json_path, "r", encoding="utf-8") as f:
    data = json.load(f)

test_texts = data

correct = 0
total = 0
all_predictions = []
all_true_labels = []
for item in test_texts:
    text = item["text"]
    true_label = item["label"]

    predicted_label, confidence = predict(text, model, tokenizer)
    
    all_predictions.append(predicted_label)
    all_true_labels.append(true_label)

    is_correct = (predicted_label == true_label)
    if is_correct:
        correct += 1
    total += 1

    print(f"Текст: {text}")
    print(f"Ожидалось: {true_label} Получено: {predicted_label} (уверенность: {confidence:.2f})")
    print(f"Результат: {'TRUE' if is_correct else 'FALSE'}")
    print("-" * 50)


accuracy = correct / total if total > 0 else 0
print(f"\nСТАТИСТИКА")
print(f"Правильных: {correct}/{total}")
print(f"Accuracy: {accuracy:.2%}")



f1_macro = f1_score(all_true_labels, all_predictions, average='macro')
f1_micro = f1_score(all_true_labels, all_predictions, average='micro')
f1_weighted = f1_score(all_true_labels, all_predictions, average='weighted')


f1_macro = f1_score(all_true_labels, all_predictions, average='macro')
f1_micro = f1_score(all_true_labels, all_predictions, average='micro')
f1_weighted = f1_score(all_true_labels, all_predictions, average='weighted')

print(f"\nF1-METRICS")
print(f"F1 Macro: {f1_macro:.4f}")
print(f"F1 Micro: {f1_micro:.4f}")
print(f"F1 Weighted: {f1_weighted:.4f}")


print(f"\nCLASSIFICATION REPORT")
print(classification_report(all_true_labels, all_predictions, 
                           target_names=['negative', 'neutral', 'positive']))

