import torch
import torch.nn as nn
from transformers import PreTrainedTokenizerFast
from huggingface_hub import hf_hub_download

repo_id = "MarkProMaster229/ClassificationSmall"

weights_path = hf_hub_download(repo_id=repo_id, filename="model_weights.pth")
tokenizer_path = hf_hub_download(repo_id=repo_id, filename="tokenizer.json")
vocab_path = hf_hub_download(repo_id=repo_id, filename="vocab.txt")

class TransformerBlock(nn.Module):
    def __init__(self, sizeVector=256, numHeads=8, dropout=0.5):
        super().__init__()
        self.ln1 = nn.LayerNorm(sizeVector)
        self.attn = nn.MultiheadAttention(sizeVector, numHeads, batch_first=True)
        self.dropout_attn = nn.Dropout(dropout)
        self.ln2 = nn.LayerNorm(sizeVector)
        self.ff = nn.Sequential(
            nn.Linear(sizeVector, sizeVector*4),
            nn.GELU(),
            nn.Linear(sizeVector*4, sizeVector),
            nn.Dropout(dropout)
        )
    
    def forward(self, x, attention_mask=None):
        key_padding_mask = ~attention_mask.bool() if attention_mask is not None else None
        h = self.ln1(x)
        attn_out, _ = self.attn(h, h, h, key_padding_mask=key_padding_mask)
        x = x + self.dropout_attn(attn_out)
        x = x + self.ff(self.ln2(x))
        return x

class TransformerRun(nn.Module):
    def __init__(self, vocabSize=120000, maxLen=100, sizeVector=256, numBlocks=4, numHeads=8, numClasses=3, dropout=0.5):
        super().__init__()
        self.token_emb = nn.Embedding(vocabSize, sizeVector)
        self.pos_emb = nn.Embedding(maxLen, sizeVector)
        self.layers = nn.ModuleList([
            TransformerBlock(sizeVector=sizeVector, numHeads=numHeads, dropout=dropout)
            for _ in range(numBlocks)
        ])
        self.dropout = nn.Dropout(dropout)
        self.ln = nn.LayerNorm(sizeVector*2)
        self.classifier = nn.Linear(sizeVector*2, numClasses)

    def forward(self, x, attention_mask=None):
        B, T = x.shape
        tok = self.token_emb(x)
        pos = self.pos_emb(torch.arange(T, device=x.device).unsqueeze(0).expand(B, T))
        h = tok + pos

        for layer in self.layers:
            h = layer(h, attention_mask)

        cls_token = h[:,0,:]
        mean_pool = h.mean(dim=1)
        combined = torch.cat([cls_token, mean_pool], dim=1)
        combined = self.ln(self.dropout(combined))
        logits = self.classifier(combined)
        return logits

config_dict = {
    'vocabSize': 119547,
    'maxLong': 100,
    'sizeVector': 256,
    'numLayers': 4,
    'numHeads': 8,
    'numClasses': 3
}

model = TransformerRun(
    vocabSize=config_dict['vocabSize'],
    maxLen=config_dict['maxLong'],
    sizeVector=config_dict['sizeVector'],
    numBlocks=config_dict['numLayers'],
    numHeads=config_dict['numHeads'],
    numClasses=config_dict['numClasses'],
    dropout=0.1
)

state_dict = torch.load(weights_path, map_location="cpu")
model.load_state_dict(state_dict)
model.eval()

tokenizer = PreTrainedTokenizerFast(
    tokenizer_file=tokenizer_path,
    vocab_file=vocab_path
)

label_map = {
    0: "positive",
    1: "negative",
    2: "neutral"
}

"""
ОСТОРОЖНО: АГРЕССИВНЫЙ КОНТЕНТ 

Комментарии взяты из открытых источников, разметка выполнена LLM.
Содержимое комментариев - личные мнения тех людей, что их оставили.
Проект создан в исследовательских целях.
Разработчик не несёт ответственности за любые прямые или косвенные 
последствия использования данных


WARNING: EXPLICIT/AGGRESSIVE CONTENT

Comments were collected from publicly available sources, with labels generated by an LLM.
The content of the comments reflects the personal opinions of their respective authors.
This project is intended for research purposes only.
All responsibility for the use of this data lies with the user.
The developer assumes no liability for any direct or indirect consequences arising from the use of this data.
"""


test_texts = [
  {
    "text": "Сириус дешевле, это где-то около 1к",
    "label": "neutral"
  },
  {
    "text": "У меня шотланд также весит",
    "label": "neutral"
  },
  {
    "text": "Бл, они же теперь харкать везде будут, месивом этим из дерьма и соли, что жуют постоянно.\\n\\nВсё в говне будет..тьфу",
    "label": "negative"
  },
  {
    "text": "Нифига, пневмонию тоже даёт и температуру 41",
    "label": "negative"
  },
  {
    "text": "Агаааха, в Москве чернота везёт с собой все болезни кому ты рассказываешь",
    "label": "negative"
  },
  {
    "text": "Ну за эту цену хотя бы минимальный Мираторг можно купить и то лучше будет",
    "label": "negative"
  },
  {
    "text": "Масло черного тмина принимайте и будет иммунитет убивать всё это",
    "label": "neutral"
  },
  {
    "text": "Я с детьми",
    "label": "neutral"
  },
  {
    "text": "Их много",
    "label": "neutral"
  },
  {
    "text": "Пару стопок в день,и похую вообще на всякие вирусы",
    "label": "negative"
  },
  {
    "text": "И это воспитание эсэсэсэср?",
    "label": "negative"
  },
  {
    "text": "значит коту не нравится, купи большое множество разных пакетиков (не только проплана) насыпь, чё будет жрать тем и корми",
    "label": "neutral"
  },
  {
    "text": "Вместе с желудком?😁",
    "label": "positive"
  },
  {
    "text": "Ты не вылечишь себя в добьешь нахуй",
    "label": "negative"
  },
  {
    "text": "Школу не хочу",
    "label": "negative"
  },
  {
    "text": "Каким надо быть дебилом, что сделать свадьбу дороже 15 к на гостя",
    "label": "negative"
  },
  {
    "text": "надо водку пить",
    "label": "neutral"
  },
  {
    "text": "Ну, можно и пузырь)",
    "label": "positive"
  },
  {
    "text": "Не удивительно",
    "label": "negative"
  },
  {
    "text": "Вы сразу к врачу или самолечением ?",
    "label": "neutral"
  },
  {
    "text": "Я живу в дальнем городе области и не МСК, весь город болеет населением 12к этой фигней. Не спорь",
    "label": "negative"
  },
  {
    "text": "Понизить демографию одним постом ✍️🙌😁",
    "label": "positive"
  },
  {
    "text": "план надежен как швейцарские часы",
    "label": "positive"
  },
  {
    "text": "Если бы ты побольше читал, то знал бы что некоторым людям из ссср сейчас 34 года всего, им еще долго до смерти",
    "label": "negative"
  },
  {
    "text": "Писец. Куда катится этот мир. Эти вот молодые люди - наше будущее 😵‍💫😵‍💫😵‍💫😵‍💫😵‍💫",
    "label": "negative"
  },
  {
    "text": "А уроки отменят ?",
    "label": "neutral"
  },
  {
    "text": "Очередная отрава для простых людей",
    "label": "negative"
  },
  {
    "text": "А так вот чо мне так плохо",
    "label": "negative"
  },
  {
    "text": "Переболел уже✌",
    "label": "positive"
  },
  {
    "text": "От МСК 400 км. При чем тут чернота, если Гонконг в другой стороне. Логически думай",
    "label": "negative"
  },
  {
    "text": "Не знаю, живу в 20 тысячном городе, не один человек не заболел",
    "label": "neutral"
  },
  {
    "text": "Причём здесь аутизм?",
    "label": "neutral"
  },
  {
    "text": "Ну впринципе неудивительно",
    "label": "negative"
  },
  {
    "text": "О я болел",
    "label": "neutral"
  },
  {
    "text": "С чего ты взял что они обманывают?",
    "label": "neutral"
  },
  {
    "text": "В Индию я вообще запретил бы ездить там вся зараза обитает",
    "label": "negative"
  },
  {
    "text": "вот ему некуда бабосы девать",
    "label": "negative"
  },
  {
    "text": "Них себе",
    "label": "neutral"
  },
  {
    "text": "Заразите пж я устала на работу ходить😂👍",
    "label": "positive"
  },
  {
    "text": "Роял нормальная только лечебная линейка, которую они как раз рекомендуют, а для постоянного кормления этот корм не подходит",
    "label": "negative"
  },
  {
    "text": "Вам повезло значит. Радуйтесь, пик в январе будет",
    "label": "negative"
  },
  {
    "text": "А причем здесь Гонконг? Это название болезни просто лол",
    "label": "negative"
  },
  {
    "text": "Да у меня паническая начинается когда последнию сигарету в пачке вижу, даже если не хочу курить иду в магазин 😅",
    "label": "neutral"
  },
  {
    "text": "А, типа нахуй самый хайповый переходный возраст не в топе?",
    "label": "negative"
  },
  {
    "text": "И че что он перекуп??",
    "label": "negative"
  },
  {
    "text": "Спасибо вам большое за совет,попробую",
    "label": "positive"
  },
  {
    "text": "Эффект плацебо действует и в другую сторону",
    "label": "neutral"
  },
  {
    "text": "Неа чо то не хочется чтобы в голове у меня какая-то железака стояло",
    "label": "negative"
  },
  {
    "text": "В Индии какой нибудь нет думаете ? Или где жара и плохая гигиена и от туда вся хворь",
    "label": "negative"
  },
  {
    "text": "Какой там гонконгский, обычный грипп типа А. Каждый год перед Новым годом все болеют",
    "label": "negative"
  },
  {
    "text": "В чем заключается их обман??",
    "label": "neutral"
  },
  {
    "text": "Завали ебало клоун тебя не спрашивали что с тобой и твоей мамкой тупой делали ты тут никто",
    "label": "negative"
  }
]
correct = 0
total = 0

for item in test_texts:
    text = item["text"]
    true_label = item["label"]
    
    inputs = tokenizer(text, return_tensors="pt", padding=True, truncation=True, max_length=config_dict['maxLong'])
    
    with torch.no_grad():
        logits = model(inputs['input_ids'])
        pred_idx = torch.argmax(logits, dim=1).item()
        pred_label = label_map[pred_idx]
    
    is_correct = (pred_label == true_label)
    if is_correct:
        correct += 1
    total += 1
    
    print(f"Текст: {text}")
    print(f"Ожидалось: {true_label} | Получено: {pred_label} (индекс: {pred_idx})")
    print(f"Результат: {'TRUE' if is_correct else 'FALSE'}")
    print("-" * 50)

accuracy = correct / total if total > 0 else 0
print(f"\n=== СТАТИСТИКА ===")
print(f"Правильных: {correct}/{total}")
print(f"Accuracy: {accuracy:.2%}")

